sonar.projectKey=simple-ci-cd
sonar.projectName=simple-ci-cd
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://15.206.146.50:9000
sonar.login=sqp_e44ddc8c41638cc8b9696a027c75ed262c3df581
